services:
  bot:
    build:
      context: .
      dockerfile: build/Dockerfile
      target: runtime
    container_name: asisa_clinic_finder_bot
    restart: unless-stopped

    volumes:
      - ./db/:/app/db
    command: >
      sh -c "task migrate && ./bot"

volumes:
  bot_data:
    driver: local
